apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-local
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          containerPort: 10090
          containerPort: 10091
          containerPort: 10092
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /prob.sh
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: p0
      protocol: TCP
      port: 10090
      targetPort: 10090
    - name: p1
      protocol: TCP
      port: 10091
      targetPort: 10091
    - name: p2
      protocol: TCP
      port: 10092
      targetPort: 10092
  type: LoadBalancer